name: Docker Maven Image CI

on: [push, pull_request]

env:
  DOCKER_PUSH: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: ./github-action.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build Images
      run: .\github-action.ps1 ${{ github.event_name }} ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
      shell: pwsh
